[package]
name = "code_reload_core"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
regex = { workspace = true }
syn = { workspace = true, features = ["full"] }