[package]
name = "code_reload_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
notify = { workspace = true }
libloading = { workspace = true }

[build-dependencies]
code_reload_build = { path = "../code_reload_build" }
