[package]
name = "code_reload"
version = "0.1.0"
edition = "2024"

[dependencies]
code_reload_core = { workspace = true }
code_reload_proc_macro = { workspace = true }
code_reload_build = { workspace = true, optional = true }

[features]
runtime = ["dep:code_reload_build"]