[package]
name = "test_demrary"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
code_reload = { path = "../code_reload" }

[build-dependencies]
code_reload = { path = "../code_reload" }
