[package]
name = "code_reload_build_script"
version = "0.1.0"
edition = "2024"

[lib]
name = "code_reload_build_script"

[[bin]]
name = "code_reload_build_script_bintest"
path = "bin/main.rs"

[dependencies]
