[package]
name = "test_library"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "run"
path = "bin/run.rs"

[dependencies]
code_reload = { path = "../code_reload" }

[build-dependencies]
code_reload_build = { path = "../code_reload_build" }
